apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: lifelink-secret-store
  namespace: {{ .Release.Namespace | quote }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | default "us-east-1" | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | default "lifelink-service-account" | quote }}
