apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
type: Opaque
data:
  database-url: {{ .Values.backend.secrets.dbUrl | b64enc | quote }}
  redis-url: {{ .Values.backend.secrets.redisUrl | b64enc | quote }}
  rabbitmq-url: {{ .Values.backend.secrets.rabbitmqUrl | b64enc | quote }}
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | b64enc | quote }}
  encryption-keys: {{ .Values.backend.secrets.encryptionKeys | b64enc | quote }}
  aws-access-key-id: {{ .Values.backend.secrets.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.backend.secrets.awsSecretAccessKey | b64enc | quote }}
  google-maps-api-key: {{ .Values.backend.secrets.googleMapsApiKey | b64enc | quote }}
  firebase-project-id: {{ .Values.backend.secrets.firebaseProjectId | b64enc | quote }}
  firebase-client-email: {{ .Values.backend.secrets.firebaseClientEmail | b64enc | quote }}
  firebase-private-key: {{ .Values.backend.secrets.firebasePrivateKey | b64enc | quote }}
